scripts:
# - script_to_run: run_system_metrics.py
#   args: []
#   interval: 20
#   threads: 1
 # - script_to_run: run_system_metrics.pl
 #  args: []
 #  interval: 20
 #  threads: 1
- script_to_run: run_process_metrics.py
  language: python
  args: ['criteria','py']
  interval: 20
  threads: 1